### ISSUE TITLE
Create function to generate a sha1 digest for a file

### ISSUE THREAD

**Issue by josh0588** [josh0588/go-file-utils#4]
For example, given a path like "/home/kim/mydata.txt", which contains the text The quick brown fox jumps over the lazy dog, return 2fd4e1c67a2d28fced849ee1bb76e7391b93eb12

**Comment by svitlana-galianova** [comment]
Hello @josh0588, I would like to get involved in your proect and explore Golang. Can I take this issue?

**Comment by josh0588** [comment]
@svitlana-galianova please do!

**Comment by svitlana-galianova** [comment]
I have tried to run the application using `go get ./...` and I have got the following error:

**main.go:13:2: local import "./fileUtils" in non-local package**

It is quite an easy fix: instead of importing "./fileUtils" you need to import "<project-name>/fileUtils".

Should I include it in my fix for this bug?

**Comment by josh0588** [comment]
oh that's weird.. i used go run main.go and it works, it throws an error when I try to change it to /fileUtils so I guess leave it out or it will break for me

**Comment by svitlana-galianova** [comment]
Ok, I will leave it like that. 
I have also created pull request for this issue. Please review it.
Pull request https://github.com/josh0588/go-file-utils/pull/6
